package playerio;

extern class PlayerIOError extends flash.errors.Error {
	var type(default,never) : PlayerIOError;
	function new(p1 : String, p2 : Int) : Void;
	static var AccessDenied : PlayerIOError;
	static var AchievementsNotLoaded : PlayerIOError;
	static var ArgumentOutOfRange : PlayerIOError;
	static var BigDBObjectDoesNotExist : PlayerIOError;
	static var BigDBObjectTooLarge : PlayerIOError;
	static var BuyingCoinsNotSupportedByProvider : PlayerIOError;
	static var CircularReference : PlayerIOError;
	static var DialogClosed : PlayerIOError;
	static var DirectPurchaseNotSupportedByProvider : PlayerIOError;
	static var ExternalError : PlayerIOError;
	static var GameDisabled : PlayerIOError;
	static var GameRequestsNotLoaded : PlayerIOError;
	static var GameRequired : PlayerIOError;
	static var GeneralError : PlayerIOError;
	static var HeartbeatFailed : PlayerIOError;
	static var IndexOutOfBounds : PlayerIOError;
	static var InternalError : PlayerIOError;
	static var InvalidArgument : PlayerIOError;
	static var InvalidAuth : PlayerIOError;
	static var InvalidBigDBKey : PlayerIOError;
	static var InvalidGameCode : PlayerIOError;
	static var InvalidIdentifier : PlayerIOError;
	static var InvalidIndexValue : PlayerIOError;
	static var InvalidMessageFormat : PlayerIOError;
	static var InvalidNotificationsEndpoint : PlayerIOError;
	static var InvalidPassword : PlayerIOError;
	static var InvalidPayVaultProviderSetup : PlayerIOError;
	static var InvalidPurchaseArguments : PlayerIOError;
	static var InvalidRegistrationData : PlayerIOError;
	static var InvalidSegment : PlayerIOError;
	static var InvalidType : PlayerIOError;
	static var ItemNotInVault : PlayerIOError;
	static var KeyAlreadyUsed : PlayerIOError;
	static var LoggedOut : PlayerIOError;
	static var MissingRoomId : PlayerIOError;
	static var MissingValue : PlayerIOError;
	static var NetworkIssue : PlayerIOError;
	static var NoServersAvailable : PlayerIOError;
	static var NotASearchColumn : PlayerIOError;
	static var NotEnoughCoins : PlayerIOError;
	static var NotObjectCreator : PlayerIOError;
	static var NotificationsNotLoaded : PlayerIOError;
	static var OneScoreNotLoaded : PlayerIOError;
	static var QuickConnectMethodNotEnabled : PlayerIOError;
	static var RoomAlreadyExists : PlayerIOError;
	static var RoomDataTooLarge : PlayerIOError;
	static var RoomIsFull : PlayerIOError;
	static var StaleVersion : PlayerIOError;
	static var UnknownAchievement : PlayerIOError;
	static var UnknownConnection : PlayerIOError;
	static var UnknownGame : PlayerIOError;
	static var UnknownIndex : PlayerIOError;
	static var UnknownPartnerPayAction : PlayerIOError;
	static var UnknownPayVaultProvider : PlayerIOError;
	static var UnknownRoom : PlayerIOError;
	static var UnknownRoomType : PlayerIOError;
	static var UnknownTable : PlayerIOError;
	static var UnknownUser : PlayerIOError;
	static var UnsupportedMethod : PlayerIOError;
	static var VaultNotLoaded : PlayerIOError;
	static var YahooNotAvailable : PlayerIOError;
	static var YahooNotLoaded : PlayerIOError;
}
